// devtoolhub/plugins/json-formatter/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';

defineProps<{ pluginId: string }>();

const rawJson = ref('');
const output = ref('');
const error = ref('');
const lastAction = ref('');
const copied = ref(false);

function formatJson() {
  try {
    const parsed = JSON.parse(rawJson.value);
    output.value = JSON.stringify(parsed, null, 2);
    error.value = '';
    lastAction.value = 'beautify';
  } catch (e) {
    error.value = (e as Error).message;
    output.value = '';
  }
}

function minifyJson() {
  try {
    const parsed = JSON.parse(rawJson.value);
    output.value = JSON.stringify(parsed);
    error.value = '';
    lastAction.value = 'minify';
  } catch (e) {
    error.value = (e as Error).message;
    output.value = '';
  }
}

function validateJson() {
  try {
    JSON.parse(rawJson.value);
    error.value = '';
    output.value = '✅ Valid JSON!';
    lastAction.value = 'validate';
  } catch (e) {
    error.value = (e as Error).message;
    output.value = '';
  }
}

async function copyOutput() {
  if (!output.value) return;
  await navigator.clipboard.writeText(output.value);
  copied.value = true;
  setTimeout(() => { copied.value = false; }, 1500);
}

function downloadJson() {
  if (!output.value) return;
  const blob = new Blob([output.value], { type: 'application/json' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'output.json';
  a.click();
  URL.revokeObjectURL(url);
}

function loadSample() {
  rawJson.value = JSON.stringify({
    name: 'DevToolHub',
    version: '1.0.0',
    plugins: ['api-tester', 'json-formatter', 'jwt-decoder'],
    meta: { framework: 'vue', port: 3002 }
  });
}
</script>

<template>
  <div :class="$style.container">
    <div :class="$style.header">
      <h2 :class="$style.title">📋 JSON Formatter</h2>
      <span :class="$style.frameworkBadge">Vue 3</span>
    </div>

    <div :class="$style.toolbar">
      <button :class="$style.actionBtn" @click="formatJson">Beautify</button>
      <button :class="$style.actionBtn" @click="minifyJson">Minify</button>
      <button :class="$style.actionBtn" @click="validateJson">Validate</button>
      <button :class="$style.ghostBtn" @click="loadSample">Load Sample</button>
    </div>

    <div :class="$style.editor">
      <div :class="$style.pane">
        <div :class="$style.paneLabel">Input JSON</div>
        <textarea
          :class="$style.textarea"
          v-model="rawJson"
          placeholder="Paste JSON here..."
          :rows="12"
          spellcheck="false"
        />
      </div>
      <div :class="$style.pane">
        <div :class="$style.paneLabel">
          Output
          <div :class="$style.outputActions" v-if="output">
            <button :class="$style.smallBtn" @click="copyOutput">{{ copied ? '✅' : '📋' }}</button>
            <button :class="$style.smallBtn" @click="downloadJson">⬇️</button>
          </div>
        </div>
        <div v-if="error" :class="$style.error">{{ error }}</div>
        <pre v-else :class="$style.outputPre">{{ output }}</pre>
      </div>
    </div>
  </div>
</template>

<style module>
.container { padding: 1.5rem; display: flex; flex-direction: column; gap: 1rem; font-family: system-ui, sans-serif; }

.header { display: flex; align-items: center; gap: 0.75rem; }
.title { margin: 0; font-size: 1.25rem; font-weight: 700; }
.frameworkBadge { background: #dcfce7; color: #166534; font-size: 0.7rem; font-weight: 700; padding: 0.2rem 0.6rem; border-radius: 999px; }

.toolbar { display: flex; gap: 0.5rem; flex-wrap: wrap; }

.actionBtn {
  padding: 0.4rem 1rem;
  background: #6366f1;
  color: #fff;
  border: none;
  border-radius: 6px;
  font-size: 0.8rem;
  font-weight: 600;
  cursor: pointer;
}

.actionBtn:hover { background: #4f46e5; }

.ghostBtn {
  padding: 0.4rem 1rem;
  background: transparent;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  font-size: 0.8rem;
  cursor: pointer;
}

.ghostBtn:hover { background: #f9fafb; }

.editor { display: flex; gap: 0.75rem; }

.pane { flex: 1; display: flex; flex-direction: column; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden; }

.paneLabel {
  padding: 0.4rem 0.75rem;
  background: #f9fafb;
  border-bottom: 1px solid #e5e7eb;
  font-size: 0.72rem;
  font-weight: 600;
  color: #6b7280;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.outputActions { display: flex; gap: 0.25rem; }

.smallBtn {
  background: none;
  border: 1px solid #e5e7eb;
  border-radius: 4px;
  padding: 0.1rem 0.4rem;
  cursor: pointer;
  font-size: 0.75rem;
}

.smallBtn:hover { background: #e5e7eb; }

.textarea {
  padding: 0.75rem;
  border: none;
  outline: none;
  font-family: 'Fira Code', monospace;
  font-size: 0.8rem;
  resize: none;
  flex: 1;
  background: #1e1e2e;
  color: #cdd6f4;
  min-height: 300px;
}

.outputPre {
  margin: 0;
  padding: 0.75rem;
  font-family: 'Fira Code', monospace;
  font-size: 0.8rem;
  background: #1e1e2e;
  color: #cdd6f4;
  overflow: auto;
  flex: 1;
  min-height: 300px;
  white-space: pre-wrap;
  word-break: break-all;
}

.error { padding: 0.75rem; color: #ef4444; font-size: 0.825rem; background: #fee2e2; flex: 1; }
</style>

// devtoolhub/plugins/regex-playground/src/App.svelte
<script lang="ts">
  export let pluginId: string;

  let pattern = '';
  let flags = 'g';
  let testString = 'The quick brown fox jumps over the lazy dog.';
  let replaceWith = '';
  let matches: RegExpMatchArray[] = [];
  let error = '';
  let showReplace = false;

  const EXAMPLES = [
    { label: 'Email', pattern: '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}', flags: 'g' },
    { label: 'URL', pattern: 'https?:\\/\\/[^\\s]+', flags: 'g' },
    { label: 'Digits', pattern: '\\d+', flags: 'g' },
    { label: 'Words', pattern: '\\b\\w+\\b', flags: 'g' },
    { label: 'IPv4', pattern: '\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b', flags: 'g' },
  ];

  function runRegex() {
    if (!pattern) {
      matches = [];
      error = '';
      return;
    }
    try {
      const re = new RegExp(pattern, flags);
      const all = [...testString.matchAll(re)];
      matches = all;
      error = '';
    } catch (e) {
      error = (e as Error).message;
      matches = [];
    }
  }

  function loadExample(ex: { pattern: string; flags: string }) {
    pattern = ex.pattern;
    flags = ex.flags;
    runRegex();
  }

  function getReplacePreview(): string {
    if (!pattern || !replaceWith) return testString;
    try {
      const re = new RegExp(pattern, flags);
      return testString.replace(re, replaceWith);
    } catch {
      return testString;
    }
  }

  $: if (pattern || testString || flags) runRegex();
</script>

<div class="container">
  <div class="header">
    <h2 class="title">🔍 Regex Playground</h2>
    <span class="frameworkBadge">Svelte</span>
  </div>

  <div class="examples">
    {#each EXAMPLES as ex}
      <button class="exBtn" on:click={() => loadExample(ex)}>{ex.label}</button>
    {/each}
  </div>

  <div class="inputRow">
    <div class="inputGroup">
      <label class="inputLabel">Pattern</label>
      <input
        class="input"
        bind:value={pattern}
        placeholder="e.g. \d+"
        spellcheck="false"
      />
    </div>
    <div class="inputGroup" style="max-width: 100px">
      <label class="inputLabel">Flags</label>
      <input class="input" bind:value={flags} placeholder="gmi" />
    </div>
  </div>

  <div class="inputGroup">
    <label class="inputLabel">Test String</label>
    <textarea class="textarea" bind:value={testString} rows={4} spellcheck="false" />
  </div>

  {#if error}
    <div class="error">⚠️ {error}</div>
  {:else}
    <div class="results">
      <div class="resultsHeader">
        <span class="resultsLabel">
          {matches.length} match{matches.length !== 1 ? 'es' : ''}
        </span>
        <button class="toggleBtn" on:click={() => showReplace = !showReplace}>
          {showReplace ? 'Hide Replace' : 'Show Replace'}
        </button>
      </div>
      {#if matches.length > 0}
        <div class="matchList">
          {#each matches as m, i}
            <div class="matchItem">
              <span class="matchIndex">#{i + 1}</span>
              <code class="matchValue">{m[0]}</code>
              <span class="matchPos">at index {m.index}</span>
            </div>
          {/each}
        </div>
      {/if}
    </div>

    {#if showReplace}
      <div class="inputGroup">
        <label class="inputLabel">Replace With</label>
        <input class="input" bind:value={replaceWith} placeholder="replacement string" />
        <div class="replacePreview">
          <span class="previewLabel">Preview:</span>
          <span class="previewText">{getReplacePreview()}</span>
        </div>
      </div>
    {/if}
  {/if}
</div>

<style>
  .container { padding: 1.5rem; display: flex; flex-direction: column; gap: 1rem; font-family: system-ui, sans-serif; }

  .header { display: flex; align-items: center; gap: 0.75rem; }
  .title { margin: 0; font-size: 1.25rem; font-weight: 700; }
  .frameworkBadge { background: #ffede8; color: #c53030; font-size: 0.7rem; font-weight: 700; padding: 0.2rem 0.6rem; border-radius: 999px; }

  .examples { display: flex; gap: 0.4rem; flex-wrap: wrap; }
  .exBtn { padding: 0.25rem 0.65rem; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 4px; font-size: 0.75rem; cursor: pointer; }
  .exBtn:hover { background: #ede9fe; border-color: #6366f1; color: #6366f1; }

  .inputRow { display: flex; gap: 0.75rem; }
  .inputGroup { display: flex; flex-direction: column; gap: 0.3rem; flex: 1; }
  .inputLabel { font-size: 0.72rem; font-weight: 600; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em; }

  .input {
    padding: 0.5rem 0.75rem;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    font-family: 'Fira Code', monospace;
    font-size: 0.85rem;
    outline: none;
  }
  .input:focus { border-color: #6366f1; }

  .textarea {
    padding: 0.75rem;
    border: 1px solid #e5e7eb;
    border-radius: 6px;
    font-family: system-ui, sans-serif;
    font-size: 0.875rem;
    resize: vertical;
    outline: none;
  }
  .textarea:focus { border-color: #6366f1; }

  .error { background: #fee2e2; color: #991b1b; padding: 0.75rem; border-radius: 6px; font-size: 0.825rem; }

  .results { display: flex; flex-direction: column; gap: 0.5rem; }
  .resultsHeader { display: flex; align-items: center; justify-content: space-between; }
  .resultsLabel { font-size: 0.8rem; font-weight: 600; color: #374151; }

  .toggleBtn { padding: 0.25rem 0.65rem; border: 1px solid #6366f1; background: transparent; color: #6366f1; border-radius: 4px; font-size: 0.75rem; cursor: pointer; }
  .toggleBtn:hover { background: #ede9fe; }

  .matchList { display: flex; flex-direction: column; gap: 0.3rem; max-height: 200px; overflow-y: auto; }
  .matchItem { display: flex; align-items: center; gap: 0.75rem; padding: 0.4rem 0.75rem; background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 6px; }
  .matchIndex { font-size: 0.7rem; color: #9ca3af; min-width: 28px; }
  .matchValue { font-family: 'Fira Code', monospace; font-size: 0.825rem; background: #ede9fe; color: #6366f1; padding: 0.1rem 0.4rem; border-radius: 4px; }
  .matchPos { font-size: 0.72rem; color: #9ca3af; margin-left: auto; }

  .replacePreview { margin-top: 0.5rem; padding: 0.6rem 0.75rem; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; }
  .previewLabel { font-size: 0.72rem; font-weight: 600; color: #166534; margin-right: 0.5rem; }
  .previewText { font-size: 0.85rem; color: #166534; }
</style>
